[book]
authors = ["Uma Roy", "ratankaliani"]
language = "en"
multilingual = false
src = "book"
title = "The OP Succinct Book"
description = "A book on all things OP Succinct"

[build]
build-dir = "target/book"

[output.html]
git-repository-url = "https://github.com/succinctlabs/op-succinct"
site-url = "/op-succinct"
additional-js = ["book/mermaid/mermaid.min.js", "book/mermaid/mermaid-init.js"]

[preprocessor.template]
before = ["links"]

[preprocessor.index]

[preprocessor.links]

[preprocessor.mermaid]
command = "mdbook-mermaid"
