[package]
name = "op-succinct-proof-utils"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]

# local
op-succinct-celestia-host-utils = { workspace = true, optional = true }
op-succinct-eigenda-host-utils = { workspace = true, optional = true }
op-succinct-elfs.workspace = true
op-succinct-ethereum-host-utils = { workspace = true, optional = true }
op-succinct-host-utils.workspace = true

# sp1
sp1-sdk.workspace = true
sp1-cluster-utils.workspace = true

# general
anyhow.workspace = true
cfg-if.workspace = true
tokio.workspace = true
tracing.workspace = true

[features]
default = ["ethereum"]
celestia = ["op-succinct-celestia-host-utils"]
eigenda = ["op-succinct-eigenda-host-utils"]
ethereum = ["op-succinct-ethereum-host-utils"]
