[package]
name = "op-succinct-ethereum-host-utils"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
#sp1
sp1-sdk.workspace = true

# local
op-succinct-client-utils.workspace = true
op-succinct-ethereum-client-utils.workspace = true
op-succinct-host-utils.workspace = true

# kona
kona-derive.workspace = true
kona-host.workspace = true
kona-preimage.workspace = true
kona-proof.workspace = true

# alloy
alloy-eips.workspace = true
alloy-primitives.workspace = true

# general
anyhow.workspace = true
async-trait.workspace = true
rkyv.workspace = true
