[package]
name = "native-host"
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
kona-host = { workspace = true }
tokio.workspace = true
clap = { workspace = true }
anyhow = { workspace = true }
