[package]
name = "op-succinct-eigenda-host-utils"
version.workspace = true
license.workspace = true
edition.workspace = true

[
dependencies
]
# sp1
<<<<<<< HEAD
sp1-sdk.workspace = true
op-succinct-eigenda-client-utils.workspace = true
op-succinct-client-utils.workspace = true
op-succinct-host-utils.workspace = true
kona-preimage.workspace = true
kona-proof.workspace = true
celo-host.workspace = true
celo-genesis.workspace = true
celo-protocol.workspace = true
hokulea-eigenda.workspace = true
hokulea-host-bin.workspace = true
hokulea-proof.workspace = true
hokulea-witgen.workspace = true
canoe-sp1-cc-host.workspace = true
canoe-verifier-address-fetcher.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
anyhow.workspace = true
async-trait.workspace = true
rkyv.workspace = true
serde_cbor.workspace = true
||||||| ae1b78c
=======
sp1-sdk.workspace = true
op-succinct-eigenda-client-utils.workspace = true
op-succinct-client-utils.workspace = true
op-succinct-host-utils.workspace = true
kona-preimage.workspace = true
kona-proof.workspace = true
hokulea-eigenda.workspace = true
hokulea-host-bin.workspace = true
hokulea-proof.workspace = true
hokulea-witgen.workspace = true
canoe-sp1-cc-host.workspace = true
canoe-verifier-address-fetcher.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
anyhow.workspace = true
async-trait.workspace = true
rkyv.workspace = true
serde_cbor.workspace = true
sp1-core-executor.workspace = true
sp1-prover.workspace = true
>>>>>>> upstream/main
sp1-core-executor = { version = "=5.2.1" }
sp1-prover = { version = "=5.2.1" }
# local
# kona
# celo-kona
# hokulea
# alloy
# general
# sp1
# local
# kona
# hokulea
# alloy
# general
