[package]
name = "op-succinct-validium-host-utils"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
# local
op-succinct-validium-client-utils.workspace = true
op-succinct-client-utils.workspace = true
op-succinct-host-utils.workspace = true
op-succinct-ethereum-client-utils.workspace = true

# kona
kona-host.workspace = true
kona-proof.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-eips.workspace = true

# sp1
sp1-sdk.workspace = true

# serialization
rkyv.workspace = true

# async
async-trait.workspace = true
tokio.workspace = true

# http
reqwest.workspace = true

# general
anyhow.workspace = true
tracing.workspace = true
