[package]
name = "op-succinct-host-utils"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]

# sp1
sp1-sdk.workspace = true

# local
op-succinct-client-utils.workspace = true
op-succinct-elfs.workspace = true

# op-alloy
op-alloy-rpc-types.workspace = true
op-alloy-network.workspace = true
op-alloy-consensus.workspace = true

# kona
kona-genesis.workspace = true
kona-protocol.workspace = true
kona-rpc.workspace = true
kona-host.workspace = true
kona-preimage.workspace = true
kona-proof.workspace = true
kona-derive.workspace = true

# hana
hana-host = { workspace = true, optional = true }

# alloy
alloy-provider.workspace = true
alloy-rlp.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-sol-types.workspace = true
alloy-eips.workspace = true
alloy-rpc-types.workspace = true
alloy-contract.workspace = true

# general
rkyv.workspace = true
serde_json.workspace = true
anyhow.workspace = true
serde_cbor.workspace = true
futures.workspace = true
num-format.workspace = true
serde.workspace = true
reqwest.workspace = true
tracing.workspace = true
async-trait.workspace = true
clap.workspace = true
strum_macros.workspace = true
strum.workspace = true
metrics.workspace = true
metrics-process.workspace = true
metrics-exporter-prometheus.workspace = true
cfg-if.workspace = true
tempfile.workspace = true

kzg-rs.workspace = true
c-kzg = "1.0.3"

[features]
default = []
celestia = ["hana-host"]
