[package]
name = "op-succinct-host-utils"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]

# sp1
sp1-sdk.workspace = true

# local
op-succinct-client-utils.workspace = true

# op-alloy
op-alloy-rpc-types.workspace = true
op-alloy-network.workspace = true
op-alloy-consensus.workspace = true
op-alloy-rpc-types-engine.workspace = true

# kona
kona-genesis.workspace = true
kona-protocol.workspace = true
kona-rpc.workspace = true

# revm
revm.workspace = true

# alloy
alloy-rpc-client.workspace = true
alloy-rpc-types.workspace = true
alloy-signer-local.workspace = true
alloy-provider.workspace = true
alloy-transport = { workspace = true, default-features = true }
alloy-transport-http = { workspace = true, default-features = true }
alloy-rlp.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-sol-types.workspace = true
alloy-eips.workspace = true
alloy-contract.workspace = true

# kona
kona-host.workspace = true
kona-preimage.workspace = true
kona-providers-alloy.workspace = true
kona-client.workspace = true
kona-proof.workspace = true
kona-mpt.workspace = true
# general
rkyv.workspace = true
serde_json.workspace = true
anyhow.workspace = true
cargo_metadata.workspace = true
serde_cbor.workspace = true
dotenv.workspace = true
tokio.workspace = true
futures.workspace = true
num-format.workspace = true
serde.workspace = true
reqwest.workspace = true
log.workspace = true
clap.workspace = true
sysinfo = "0.32.0"
async-trait.workspace = true
tracing.workspace = true
