[package]
name = "op-succinct-host-utils"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]

# workspace
alloy.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-sol-types.workspace = true
rkyv.workspace = true
serde_json.workspace = true
anyhow.workspace = true
cargo_metadata.workspace = true
serde_cbor.workspace = true
dotenv.workspace = true
tokio.workspace = true
futures.workspace = true
num-format.workspace = true
serde.workspace = true
reqwest.workspace = true

# sp1
sp1-sdk.workspace = true

# local
op-succinct-client-utils.workspace = true

# op-alloy
op-alloy-genesis.workspace = true

# kona
kona-host.workspace = true
kona-primitives.workspace = true
