[package]
name = "zkvm-host"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "script"
path = "bin/script.rs"

[[bin]]
name = "cost_estimator"
path = "bin/cost_estimator.rs"

[dependencies]

# workspace
hex.workspace = true
rkyv.workspace = true
alloy-primitives = { workspace = true, features = ["serde"] }
alloy-sol-types = { workspace = true }
ethers = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }

# kona
kona-host = { workspace = true }

# local
zkvm-common = { path = "../common" }
native-host = { path = "../native-host" }

# sp1
sp1-sdk = { workspace = true }
sp1-core = { workspace = true }
anyhow.workspace = true
num-format = "0.4.4"
dotenv = "0.15.0"
cargo_metadata = "0.18.1"

[build-dependencies]
sp1-helper = { workspace = true }
