[package]
name = "range-eigenda"
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[
dependencies
]
# general
<<<<<<< HEAD
rkyv.workspace = true
serde_cbor.workspace = true
kona-proof.workspace = true
hokulea-proof.workspace = true
hokulea-zkvm-verification.workspace = true
canoe-sp1-cc-verifier.workspace = true
canoe-verifier-address-fetcher.workspace = true
sp1-zkvm.workspace = true
op-succinct-client-utils.workspace = true
op-succinct-eigenda-client-utils.workspace = true
||||||| ae1b78c
=======
rkyv.workspace = true
serde_cbor.workspace = true
kona-proof.workspace = true
hokulea-proof.workspace = true
hokulea-zkvm-verification.workspace = true
canoe-sp1-cc-verifier.workspace = true
canoe-verifier-address-fetcher.workspace = true
sp1-zkvm.workspace = true
op-succinct-client-utils.workspace = true
op-succinct-eigenda-client-utils.workspace = true
op-succinct-range-utils.workspace = true
>>>>>>> upstream/main
# kona
# hokulea
# sp1
# op-succinct
op-succinct-range-utils = { workspace = true, features = [
    "tracing-subscriber",
] }
# `tracing-subscriber` feature dependencies
tracing-subscriber = { workspace = true, optional = true }
# general
# kona
# hokulea
# sp1
# op-succinct
# `tracing-subscriber` feature dependencies

[features]
embedded = ["sp1-zkvm/embedded"]
tracing-subscriber = ["dep:tracing-subscriber"]
