[package]
name = "range-eigenda"
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# general
rkyv.workspace = true
serde_cbor.workspace = true

# kona
kona-proof.workspace = true

# hokulea
hokulea-proof.workspace = true
hokulea-zkvm-verification.workspace = true

# sp1
sp1-zkvm.workspace = true

# op-succinct
op-succinct-client-utils.workspace = true
op-succinct-eigenda-client-utils.workspace = true
op-succinct-range-utils = { workspace = true, features = [
    "tracing-subscriber",
] }

# `tracing-subscriber` feature dependencies
tracing-subscriber = { workspace = true, optional = true }

[features]
embedded = ["sp1-zkvm/embedded"]
tracing-subscriber = ["dep:tracing-subscriber"]
