name: Cycle Count Diff - Celestia

on:
  workflow_dispatch:
  # pull_request:
  #   paths:
  #     - 'elf/celestia-range-elf-embedded'

jobs:
  cycle-count-diff-celestia:
    runs-on:
      - runs-on
      - cpu=32
      - ram=128
      - family=m7a+m7i-flex
      - image=ubuntu22-full-x64
      - run-id=${{ github.run_id }}
      - disk=large
      - spot=false
      
    steps:
      - name: Checkout Repository (for local actions)
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup
        with:
           submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-d592b3e0f142d694c3be539702704a4a73238773

      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: new_code
          submodules: recursive

      - name: Checkout Base Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: old_code
          submodules: recursive

      - name: Run Test On New Branch
        run: |
          RUST_LOG=info NEW_BRANCH=true cargo test test_cycle_count_diff --release --features celestia -- --exact --nocapture
        working-directory: ./new_code
        env:
          L2_NODE_RPC: ${{ secrets.L2_CELESTIA_RPC }}
          L1_RPC: ${{ secrets.L1_RPC }}
          L1_BEACON_RPC: ${{ secrets.L1_BEACON_RPC }}
          L2_RPC: ${{ secrets.L2_CELESTIA_RPC }}
          CELESTIA_CONNECTION: ${{ secrets.CELESTIA_CONNECTION }}
          NAMESPACE: 097f271de1df26ba
          CELESTIA_INDEXER_RPC: ${{ secrets.CELESTIA_INDEXER_RPC }}

      - name: Copy Stats File For Old Branch
        run: |
          STATS_FILE=$(find ${{ github.workspace }}/new_code -name "new_cycle_stats.json" -type f | head -1)
          cp "$STATS_FILE" ${{ github.workspace }}/old_code/scripts/prove/new_cycle_stats.json

      - name: Run Test On Old Branch
        run: |
          RUST_LOG=info NEW_BRANCH=false cargo test test_cycle_count_diff --release --features celestia -- --exact --nocapture
        working-directory: ./old_code
        env:
          L2_NODE_RPC: ${{ secrets.L2_CELESTIA_RPC }}
          L1_RPC: ${{ secrets.L1_RPC }}
          L1_BEACON_RPC: ${{ secrets.L1_BEACON_RPC }}
          L2_RPC: ${{ secrets.L2_CELESTIA_RPC }}
          CELESTIA_CONNECTION: ${{ secrets.CELESTIA_CONNECTION }}
          NAMESPACE: 097f271de1df26ba
          CELESTIA_INDEXER_RPC: ${{ secrets.CELESTIA_INDEXER_RPC }}

      - name: Compare Results And Post To Github
        run: |
          RUST_LOG=info cargo test --test cycle_count_diff test_post_to_github --features celestia -- --exact --nocapture
        working-directory: ./old_code
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POST_TO_GITHUB: ${{ github.event_name == 'pull_request' }}
