# This workflow runs on all PRs, and ensures that the ELF files are built correctly.

name: ELF

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.pdf'
      - '**/*.md'
  push:
    tags:
      - v[0-9]+.*
    branches:
      - "release/*"
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main' }}

jobs:
  elf:
    runs-on:
      - runs-on
      - runner=64cpu-linux-x64
      - run-id=${{ github.run_id }}
      - spot=false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up
          ~/.sp1/bin/cargo-prove prove --version
          source ~/.bashrc
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Build and verify ELF files
        run: |
          just build-elfs

          # Check for any changes in the elf directory
          if [ -n "$(git status --porcelain elf/)" ]; then
            echo "❌ ELF files changed during build!"
            git diff
            exit 1
          else
            echo "✅ ELF files remained unchanged"
          fi
