name: ELF

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  elf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version
          source ~/.bashrc
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Verify the OP Succinct binaries
        run: |
          # Build the binaries
          cd programs/range
          ~/.sp1/bin/cargo-prove prove build --elf-name range-elf --docker --tag v4.0.0-rc.10 --output-directory ../../elf
          cd ../aggregation
          ~/.sp1/bin/cargo-prove prove build --elf-name aggregation-elf --docker --tag v4.0.0-rc.10 --output-directory ../../elf
          cd ../../

          # Check for any changes in the elf directory
          if [ -n "$(git status --porcelain elf/)" ]; then
            echo "❌ ELF files changed during build!"
            git diff
            exit 1
          else
            echo "✅ ELF files remained unchanged"
          fi
